services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    depends_on:
      - my-db

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - PYTHONUNBUFFERED=1

    depends_on:
      - my-db

  simulator:
    build: .
    command: python simulator.py
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - my-db

  my-db:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: