version: '3.8'

services:
  # השירות של האתר (הדשבורד)
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_TOKEN=8332723549:AAHDda8VLo_RrBW5jeokcEntUB8J0t0b9CI
      - CHAT_ID=770737566
    depends_on:
      - my-db

  # השירות החדש של הבוט בטלגרם
  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TELEGRAM_TOKEN=8332723549:AAHDda8VLo_RrBW5jeokcEntUB8J0t0b9CI
      - CHAT_ID=770737566
    depends_on:
      - my-db

  # מסד הנתונים ששניהם משתמשים בו
  my-db:
    image: redis:alpine
