version: '3.8'

services:
  # השירות של האתר (הדשבורד)
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    depends_on:
      - my-db

  # השירות החדש של הבוט
  bot:
    build: .
    command: python bot.py
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    depends_on:
      - my-db

  # מסד הנתונים ששניהם משתמשים בו
  my-db:
    image: redis:alpine
