name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # ה-Pipeline ירוץ בכל פעם שתעשה Push לענף הראשי

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} # מיד נגדיר גם את זה
          username: ronengilboz # שם המשתמש שלך בשרת
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/camera_project
            git pull origin main
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env
            echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
            docker compose up -d --build
